//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManufacturingExecutionSystem.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ManufacturingExecutionSystem.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 OPENING DEVICE... 的本地化字符串。
        /// </summary>
        internal static string btn_OpenDevice_Click_label_MessageInfo {
            get {
                return ResourceManager.GetString("btn_OpenDevice_Click_label_MessageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ENUMERATING DEVICES... 的本地化字符串。
        /// </summary>
        internal static string btn_ScanDevice_Click_Label_MessageInfo {
            get {
                return ResourceManager.GetString("btn_ScanDevice_Click_Label_MessageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CLOSING APPLICATION... 的本地化字符串。
        /// </summary>
        internal static string CameraApplication_FormClose {
            get {
                return ResourceManager.GetString("CameraApplication_FormClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CLOSE DEVICE SUCCEED 的本地化字符串。
        /// </summary>
        internal static string CloseDeviceSucceed {
            get {
                return ResourceManager.GetString("CloseDeviceSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DIVICE OPEN FAILED! 的本地化字符串。
        /// </summary>
        internal static string Device_Open_Failed {
            get {
                return ResourceManager.GetString("Device_Open_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DIVICE OPEN SUCCEED 的本地化字符串。
        /// </summary>
        internal static string Device_Open_Succeed {
            get {
                return ResourceManager.GetString("Device_Open_Succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ENUMERATE DEVICES FAILED! 的本地化字符串。
        /// </summary>
        internal static string Enum_Devices_Failed {
            get {
                return ResourceManager.GetString("Enum_Devices_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ENUMERATE DEVICES SUCCEED 的本地化字符串。
        /// </summary>
        internal static string Enum_Devices_Succeed {
            get {
                return ResourceManager.GetString("Enum_Devices_Succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 曝光时间 的本地化字符串。
        /// </summary>
        internal static string ExposureTime {
            get {
                return ResourceManager.GetString("ExposureTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帧/秒 的本地化字符串。
        /// </summary>
        internal static string ExposureTimeUnit {
            get {
                return ResourceManager.GetString("ExposureTimeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采集帧率： 的本地化字符串。
        /// </summary>
        internal static string FrameRate {
            get {
                return ResourceManager.GetString("FrameRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 增益： 的本地化字符串。
        /// </summary>
        internal static string Gain {
            get {
                return ResourceManager.GetString("Gain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GET PAYLOADSIZE FAILED! 的本地化字符串。
        /// </summary>
        internal static string GetPayloadSizeFailed {
            get {
                return ResourceManager.GetString("GetPayloadSizeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求超时或密码错误！请重试。 的本地化字符串。
        /// </summary>
        internal static string LoginPassWordErro {
            get {
                return ResourceManager.GetString("LoginPassWordErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求超时！请重试。 的本地化字符串。
        /// </summary>
        internal static string RequestTimeOut {
            get {
                return ResourceManager.GetString("RequestTimeOut", resourceCulture);
            }
        }
    }
}
